title: Example page
author: Nayef 
email: nayef.ahmad@vch.ca
description: > # this means to ignore newlines until "baseurl:"
  This is an example of a page 

# social links
twitter_username: your-twitter-handle
github_username:  nayefahmad

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
